// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_00HmSdbBcS07jAanlqCUL5MjFEkMHQ',
    appId: '1:1002496221890:web:16ef860f7ac1af8c6c515b',
    messagingSenderId: '1002496221890',
    projectId: 'yegestao',
    authDomain: 'yegestao.firebaseapp.com',
    storageBucket: 'yegestao.appspot.com',
    measurementId: 'G-S0DYL6MZM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4u85nsUX8Jvuv8KzGWj8PgasZx_nrGA',
    appId: '1:1002496221890:android:e2c837e2b3a1dc566c515b',
    messagingSenderId: '1002496221890',
    projectId: 'yegestao',
    storageBucket: 'yegestao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBvb-zB0OahWIlqm2Ajyws3Wk8OwJ42L4',
    appId: '1:1002496221890:ios:ab9d5268811fafb46c515b',
    messagingSenderId: '1002496221890',
    projectId: 'yegestao',
    storageBucket: 'yegestao.appspot.com',
    iosClientId: '1002496221890-jcvlavtckvh9g3oh1rof4nlrh6rm883b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBvb-zB0OahWIlqm2Ajyws3Wk8OwJ42L4',
    appId: '1:1002496221890:ios:ab9d5268811fafb46c515b',
    messagingSenderId: '1002496221890',
    projectId: 'yegestao',
    storageBucket: 'yegestao.appspot.com',
    iosClientId: '1002496221890-jcvlavtckvh9g3oh1rof4nlrh6rm883b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU_00HmSdbBcS07jAanlqCUL5MjFEkMHQ',
    appId: '1:1002496221890:web:c17edb4c440f84966c515b',
    messagingSenderId: '1002496221890',
    projectId: 'yegestao',
    authDomain: 'yegestao.firebaseapp.com',
    storageBucket: 'yegestao.appspot.com',
    measurementId: 'G-MX5V6JGCQC',
  );

}